
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloSvc", targetNamespace = "http://svc.webage.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloSvc {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://svc.webage.com/", className = "client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://svc.webage.com/", className = "client.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param courseId
     * @return
     *     returns client.Course
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTrainingClass", targetNamespace = "http://svc.webage.com/", className = "client.GetTrainingClass")
    @ResponseWrapper(localName = "getTrainingClassResponse", targetNamespace = "http://svc.webage.com/", className = "client.GetTrainingClassResponse")
    public Course getTrainingClass(
        @WebParam(name = "courseId", targetNamespace = "")
        int courseId);

}
